//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoReferenciaAreaDePoligonos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tarefa04soap/", ConfigurationName="ServicoReferenciaAreaDePoligonos.InterfaceAreaDePoligonos")]
    public interface InterfaceAreaDePoligonos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrianguloRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrianguloResponse")]
        ServicoReferenciaAreaDePoligonos.areaTrianguloResponse areaTriangulo(ServicoReferenciaAreaDePoligonos.areaTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrianguloRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrianguloResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaTrianguloResponse> areaTrianguloAsync(ServicoReferenciaAreaDePoligonos.areaTrianguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaRetanguloRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaRetanguloResponse")]
        ServicoReferenciaAreaDePoligonos.areaRetanguloResponse areaRetangulo(ServicoReferenciaAreaDePoligonos.areaRetanguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaRetanguloRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaRetanguloResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaRetanguloResponse> areaRetanguloAsync(ServicoReferenciaAreaDePoligonos.areaRetanguloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaPentagonoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaPentagonoResponse")]
        ServicoReferenciaAreaDePoligonos.areaPentagonoResponse areaPentagono(ServicoReferenciaAreaDePoligonos.areaPentagonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaPentagonoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaPentagonoResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaPentagonoResponse> areaPentagonoAsync(ServicoReferenciaAreaDePoligonos.areaPentagonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaHexagonoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaHexagonoResponse")]
        ServicoReferenciaAreaDePoligonos.areaHexagonoResponse areaHexagono(ServicoReferenciaAreaDePoligonos.areaHexagonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaHexagonoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaHexagonoResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaHexagonoResponse> areaHexagonoAsync(ServicoReferenciaAreaDePoligonos.areaHexagonoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaLosangoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaLosangoResponse")]
        ServicoReferenciaAreaDePoligonos.areaLosangoResponse areaLosango(ServicoReferenciaAreaDePoligonos.areaLosangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaLosangoRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaLosangoResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaLosangoResponse> areaLosangoAsync(ServicoReferenciaAreaDePoligonos.areaLosangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrapezioRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrapezioResponse")]
        ServicoReferenciaAreaDePoligonos.areaTrapezioResponse areaTrapezio(ServicoReferenciaAreaDePoligonos.areaTrapezioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrapezioRequest", ReplyAction="http://tarefa04soap/InterfaceAreaDePoligonos/areaTrapezioResponse")]
        System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaTrapezioResponse> areaTrapezioAsync(ServicoReferenciaAreaDePoligonos.areaTrapezioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaTriangulo", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaTrianguloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public areaTrianguloRequest()
        {
        }
        
        public areaTrianguloRequest(double arg0, double arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaTrianguloResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaTrianguloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaTrianguloResponse()
        {
        }
        
        public areaTrianguloResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaRetangulo", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaRetanguloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public areaRetanguloRequest()
        {
        }
        
        public areaRetanguloRequest(double arg0, double arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaRetanguloResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaRetanguloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaRetanguloResponse()
        {
        }
        
        public areaRetanguloResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaPentagono", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaPentagonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public areaPentagonoRequest()
        {
        }
        
        public areaPentagonoRequest(double arg0, double arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaPentagonoResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaPentagonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaPentagonoResponse()
        {
        }
        
        public areaPentagonoResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaHexagono", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaHexagonoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public areaHexagonoRequest()
        {
        }
        
        public areaHexagonoRequest(double arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaHexagonoResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaHexagonoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaHexagonoResponse()
        {
        }
        
        public areaHexagonoResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaLosango", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaLosangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public areaLosangoRequest()
        {
        }
        
        public areaLosangoRequest(double arg0, double arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaLosangoResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaLosangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaLosangoResponse()
        {
        }
        
        public areaLosangoResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaTrapezio", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaTrapezioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public double arg2;
        
        public areaTrapezioRequest()
        {
        }
        
        public areaTrapezioRequest(double arg0, double arg1, double arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="areaTrapezioResponse", WrapperNamespace="http://tarefa04soap/", IsWrapped=true)]
    public partial class areaTrapezioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public areaTrapezioResponse()
        {
        }
        
        public areaTrapezioResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface InterfaceAreaDePoligonosChannel : ServicoReferenciaAreaDePoligonos.InterfaceAreaDePoligonos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class InterfaceAreaDePoligonosClient : System.ServiceModel.ClientBase<ServicoReferenciaAreaDePoligonos.InterfaceAreaDePoligonos>, ServicoReferenciaAreaDePoligonos.InterfaceAreaDePoligonos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceAreaDePoligonosClient() : 
                base(InterfaceAreaDePoligonosClient.GetDefaultBinding(), InterfaceAreaDePoligonosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicoAreaDePoligonosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceAreaDePoligonosClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceAreaDePoligonosClient.GetBindingForEndpoint(endpointConfiguration), InterfaceAreaDePoligonosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceAreaDePoligonosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceAreaDePoligonosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceAreaDePoligonosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceAreaDePoligonosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceAreaDePoligonosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicoReferenciaAreaDePoligonos.areaTrianguloResponse areaTriangulo(ServicoReferenciaAreaDePoligonos.areaTrianguloRequest request)
        {
            return base.Channel.areaTriangulo(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaTrianguloResponse> areaTrianguloAsync(ServicoReferenciaAreaDePoligonos.areaTrianguloRequest request)
        {
            return base.Channel.areaTrianguloAsync(request);
        }
        
        public ServicoReferenciaAreaDePoligonos.areaRetanguloResponse areaRetangulo(ServicoReferenciaAreaDePoligonos.areaRetanguloRequest request)
        {
            return base.Channel.areaRetangulo(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaRetanguloResponse> areaRetanguloAsync(ServicoReferenciaAreaDePoligonos.areaRetanguloRequest request)
        {
            return base.Channel.areaRetanguloAsync(request);
        }
        
        public ServicoReferenciaAreaDePoligonos.areaPentagonoResponse areaPentagono(ServicoReferenciaAreaDePoligonos.areaPentagonoRequest request)
        {
            return base.Channel.areaPentagono(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaPentagonoResponse> areaPentagonoAsync(ServicoReferenciaAreaDePoligonos.areaPentagonoRequest request)
        {
            return base.Channel.areaPentagonoAsync(request);
        }
        
        public ServicoReferenciaAreaDePoligonos.areaHexagonoResponse areaHexagono(ServicoReferenciaAreaDePoligonos.areaHexagonoRequest request)
        {
            return base.Channel.areaHexagono(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaHexagonoResponse> areaHexagonoAsync(ServicoReferenciaAreaDePoligonos.areaHexagonoRequest request)
        {
            return base.Channel.areaHexagonoAsync(request);
        }
        
        public ServicoReferenciaAreaDePoligonos.areaLosangoResponse areaLosango(ServicoReferenciaAreaDePoligonos.areaLosangoRequest request)
        {
            return base.Channel.areaLosango(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaLosangoResponse> areaLosangoAsync(ServicoReferenciaAreaDePoligonos.areaLosangoRequest request)
        {
            return base.Channel.areaLosangoAsync(request);
        }
        
        public ServicoReferenciaAreaDePoligonos.areaTrapezioResponse areaTrapezio(ServicoReferenciaAreaDePoligonos.areaTrapezioRequest request)
        {
            return base.Channel.areaTrapezio(request);
        }
        
        public System.Threading.Tasks.Task<ServicoReferenciaAreaDePoligonos.areaTrapezioResponse> areaTrapezioAsync(ServicoReferenciaAreaDePoligonos.areaTrapezioRequest request)
        {
            return base.Channel.areaTrapezioAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoAreaDePoligonosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoAreaDePoligonosPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9876/areapoligonos");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceAreaDePoligonosClient.GetBindingForEndpoint(EndpointConfiguration.ServicoAreaDePoligonosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceAreaDePoligonosClient.GetEndpointAddress(EndpointConfiguration.ServicoAreaDePoligonosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicoAreaDePoligonosPort,
        }
    }
}
